

title: shenjun
email: 805442858@qq.com
baseurl: /
github_username:  shenjunjkl

#rss
name: shenjun's blog
description: ‘description’
url: "http://shenjunjkl.github.io"

paginate: 6
#version: 2.1.0

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Permalinks
permalink:        pretty
#relative_permalinks: true

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
