

title: shenjun
email: your-email@domain.com
description: ‘测试下中文的description有没有问题’
baseurl: /
url: ""
#twitter_username: jekyllrb
github_username:  shenjunjkl

paginate: 8
#version: 2.1.0

# Build settings
markdown: kramdown
highlighter: pygments
theme: minima

# Permalinks
permalink:        pretty
#relative_permalinks: true

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
